a = int(input("first number \t"))
b = int(input("second number \t"))
if a > 0 and b > 0:
    print(f"a+b = {a + b}")
    print(f"a-b = {a - b}")
    print(f"a/b = {a / b}")
    print(f"a*b = {a * b}")
    print(f"a//b = {a // b}")
    print(f"a%b = {a % b}")
    print(f"a>b = {a > b}")
    print(f"a<b = {a < b}")
    print(f"a==b = {a == b}")
    print(f"a>=b = {a >= b}")
    print(f"a<=b = {a <= b}")
    print(f"a!=b = {a != b}")
    print(f"a**b = {a**b}")
    print(f"abs((-a)+(-b)) = {abs((-a)+(-b))}")
